import { DownloadIcon, ReportIcon } from '@/shared/components/icons';
import {
  Badge,
  Button,
  Card,
  CardHeader,
  EmptyState,
  ErrorState,
  Pagination,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeaderCell,
  TableRow,
  TableSkeleton,
  TableWrapper,
} from '@/shared/components/ui';

import { REPORT_FORMAT_LABELS, REPORT_TYPES } from '../constants';
import type { GeneratedReport, HistoryViewState } from '../types';

export interface ReportHistoryPanelProps {
  viewState: HistoryViewState;
  reports: GeneratedReport[];
  page: number;
  pageSize: number;
  totalItems: number;
  onPageChange: (page: number) => void;
  onRetry: () => void;
  onDownload: (report: GeneratedReport) => void;
}

function toDisplayDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-PH', { year: 'numeric', month: 'short', day: 'numeric' });
}

function reportTypeLabel(reportType: GeneratedReport['reportType']): string {
  return REPORT_TYPES.find((type) => type.id === reportType)?.label ?? reportType;
}

/** Reads from the `Report` model — one row is written every time Export succeeds. */
export function ReportHistoryPanel({
  viewState,
  reports,
  page,
  pageSize,
  totalItems,
  onPageChange,
  onRetry,
  onDownload,
}: ReportHistoryPanelProps) {
  return (
    <Card className="mt-5">
      <CardHeader title="Report History" subtitle={viewState === 'ready' ? `${totalItems.toLocaleString()} generated` : undefined} />

      {viewState === 'loading' ? <TableSkeleton rows={4} columns={5} /> : null}

      {viewState === 'error' ? (
        <ErrorState onRetry={onRetry} description="We could not load report history. Check your connection and try again." />
      ) : null}

      {viewState === 'ready' && reports.length === 0 ? (
        <EmptyState
          icon={ReportIcon}
          title="No reports generated yet"
          description="Reports you export will be listed here for re-download."
        />
      ) : null}

      {viewState === 'ready' && reports.length > 0 ? (
        <>
          <TableWrapper>
            <Table caption="Previously generated reports">
              <TableHead>
                <TableRow>
                  <TableHeaderCell>Title</TableHeaderCell>
                  <TableHeaderCell>Type</TableHeaderCell>
                  <TableHeaderCell>Generated By</TableHeaderCell>
                  <TableHeaderCell>Date</TableHeaderCell>
                  <TableHeaderCell>Format</TableHeaderCell>
                  <TableHeaderCell>
                    <span className="sr-only">Actions</span>
                  </TableHeaderCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {reports.map((report) => (
                  <TableRow key={report.id}>
                    <TableCell>
                      <span className="whitespace-nowrap font-semibold text-ink">{report.title}</span>
                    </TableCell>
                    <TableCell>
                      <Badge tone="blue">{reportTypeLabel(report.reportType)}</Badge>
                    </TableCell>
                    <TableCell>
                      <span className="whitespace-nowrap">{report.generatedByName ?? '—'}</span>
                    </TableCell>
                    <TableCell>
                      <span className="whitespace-nowrap">{toDisplayDate(report.generatedAt)}</span>
                    </TableCell>
                    <TableCell>
                      <Badge tone="gray">{REPORT_FORMAT_LABELS[report.format]}</Badge>
                    </TableCell>
                    <TableCell>
                      <Button
                        variant="outline"
                        size="sm"
                        leadingIcon={<DownloadIcon aria-hidden />}
                        onClick={() => onDownload(report)}
                      >
                        Download
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </TableWrapper>

          <Pagination
            className="mt-4"
            page={page}
            pageSize={pageSize}
            totalItems={totalItems}
            onPageChange={onPageChange}
            itemLabel="reports"
          />
        </>
      ) : null}
    </Card>
  );
}
